#!/bin/sh
sudo systemctl start docker
sudo docker run -d --rm --name some-nginx -v /home/moritz/git/not_synced/webauthn:/usr/share/nginx/html:ro -p 8080:80 nginx
chromium http:localhost:8080/test.html
